/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Accounts;
import model.CurrentUser;
import model.GradingSystem;
import service.implementations.AccountsServiceImplementation;
import service.implementations.UserServiceImplementation;
import service.interfaces.AccountsServiceInterface;
import service.interfaces.UserServiceInterface;
import tools.ErrorException;
import tools.Transparent;

/**
 *
 * @author sam
 */
public class confirm extends javax.swing.JDialog {

    private javax.swing.JFrame parentFrame;
    private UserServiceInterface userService;
    private AccountsServiceInterface accountService;
    private CurrentUser user;
    private JFrame chFrame;
    
    /**
     * Creates new form confirm
     */
    public confirm(java.awt.Frame parent, boolean modal, CurrentUser currentUser, javax.swing.JFrame cHome) {
        super(parent, modal);
        Transparent trans = new Transparent();
        trans.TransparentDForm(this);
        initComponents();
        this.setSize( 500, 315);
        this.setLocationRelativeTo(null);
        this.parentFrame = (JFrame) parent;
        user = currentUser;
        chFrame = cHome;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPasswordField1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(190, 130, 250, 30);

        jLabel2.setFont(new java.awt.Font("DK Crayon Crumble", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 140, 90, 20);

        confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/continue.jpg"))); // NOI18N
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm);
        confirm.setBounds(190, 190, 130, 30);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancel.jpg"))); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(340, 190, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/confirm.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        userService = new UserServiceImplementation();
        accountService = new AccountsServiceImplementation();
        Accounts st = new Accounts();
        ArrayList<Accounts> accountSearch = new ArrayList<>();
        st.setUsername(user.getCurrentUser());
        try {
            accountSearch = accountService.getAccounts(st);
        } catch (ErrorException ex) {
            Logger.getLogger(confirm.class.getName()).log(Level.SEVERE, null, ex);
        }
        for ( Accounts temp : accountSearch )
        {
            if (temp.getPassword().equalsIgnoreCase(jPasswordField1.getText()))
            {
                System.out.println(temp.getPassword());
                Home home = new Home();
            
                try {
                    userService.deleteUser(user.getUserID());
                    accountService.deleteAccounts(user.getUserID());
            
                } catch (ErrorException ex) {
                    Logger.getLogger(confirm.class.getName()).log(Level.SEVERE, null, ex);
                }
            
                this.dispose();
                chFrame.dispose();
                home.setVisible(true);
                JOptionPane.showMessageDialog(this, "Your account has been deleted from the system!", "Successful", JOptionPane.INFORMATION_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(this, "Invalid Password!", "Error", JOptionPane.ERROR_MESSAGE);
        
        }
        
        
    }//GEN-LAST:event_confirmActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
        confirm.doClick();
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
