/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFrame;
import tools.Transparent;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.Accounts;
import model.CurrentUser;
import service.implementations.AccountsServiceImplementation;
import service.interfaces.AccountsServiceInterface;
import tools.ErrorException;

/**
 *
 * @author sam
 */
public class editPassword extends javax.swing.JDialog {

    private javax.swing.JFrame parentFrame;
    /**
     * Creates new form editPassword
     */
    private CurrentUser userCurrent;

    public editPassword(java.awt.Frame parent, boolean modal, CurrentUser currentUser) {
        super(parent, modal);
        Transparent trans = new Transparent();
        trans.TransparentDForm(this);
        initComponents();
        userCurrent = currentUser;
        this.setSize(500, 350);
        this.setLocationRelativeTo(null);
        this.parentFrame = (JFrame) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ccurrentPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        cnewPass = new javax.swing.JPasswordField();
        cretypePass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("DK Crayon Crumble", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Current Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 120, 150, 19);

        ccurrentPass.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        ccurrentPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccurrentPassActionPerformed(evt);
            }
        });
        jPanel1.add(ccurrentPass);
        ccurrentPass.setBounds(210, 120, 243, 30);

        jLabel5.setFont(new java.awt.Font("DK Crayon Crumble", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 160, 95, 19);

        cnewPass.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        cnewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnewPassActionPerformed(evt);
            }
        });
        jPanel1.add(cnewPass);
        cnewPass.setBounds(210, 159, 243, 30);

        cretypePass.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        cretypePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cretypePassActionPerformed(evt);
            }
        });
        jPanel1.add(cretypePass);
        cretypePass.setBounds(210, 199, 243, 30);

        jLabel6.setFont(new java.awt.Font("DK Crayon Crumble", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Retype Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 200, 114, 19);

        ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/continue.jpg"))); // NOI18N
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok);
        ok.setBounds(210, 240, 130, 30);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel.jpg"))); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel);
        cancel.setBounds(350, 240, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/editPassFrame.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        AccountsServiceInterface accountService = new AccountsServiceImplementation();
        Accounts account = new Accounts();
        try {
            account = accountService.getAccount(userCurrent.getCurrentUser());
        } catch (ErrorException ex) {
            ex.printStackTrace();
        }
        String currentPass = ccurrentPass.getText();
        String newPass = cnewPass.getText();
        String retypePass = cretypePass.getText();
        int newPassLength = newPass.length();
        boolean readyCode = false;
        if (account.getPassword().equalsIgnoreCase(currentPass)) {
            readyCode = true;
            ccurrentPass.setBackground(null);
        } else {
            ccurrentPass.setBackground(Color.red);
            //errorField();
        }
        if (newPass.isEmpty() || retypePass.isEmpty() || currentPass.isEmpty()) {
            passEmtpty();
        } else {
            boolean ready = false;
            if (!newPass.equals(retypePass) && !currentPass.isEmpty()) {
                System.out.print("baluga");
                cnewPass.setBackground(Color.red);
                cretypePass.setBackground(null);
            } else {
                cnewPass.setBackground(null);
                if (newPass.equals(retypePass)) {
                    if (newPassLength < 6 || newPassLength > 15) {
                        cnewPass.setText("minimum of 6 maximum of 15");
                        cretypePass.setText("minimum of 6 maximum of 15");
                        cnewPass.setBackground(Color.red);
                        cretypePass.setBackground(Color.red);
                    } else {
                        ready = true;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Password didn't Match", "Error", JOptionPane.ERROR_MESSAGE);
                    passEmtpty();
                }

            }

            if (readyCode) {

                if (ready) {

                    cnewPass.setBackground(null);
                    cretypePass.setBackground(null);
                    ccurrentPass.setBackground(null);

                    if (newPass.equals(retypePass)) {

                        account.setPassword(newPass);
                        account.setUserID(userCurrent.getUserID());
                        try {
                            accountService.editAccounts(account);
                        } catch (ErrorException ex) {
                            ex.printStackTrace();
                        }
                        this.dispose();
                        JOptionPane.showMessageDialog(this, "You have succesfully changed your password!", "Succesful", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        cnewPass.setBackground(Color.red);
                        cretypePass.setBackground(Color.red);
                    }


                } else {
                    ccurrentPass.setBackground(Color.red);
                }
            }
        }


    }//GEN-LAST:event_okActionPerformed
    public void passEmtpty() {
        String currentPass = ccurrentPass.getText();
        String newPass = cnewPass.getText();
        String retypePass = cretypePass.getText();
        if (newPass.isEmpty()) {
            cnewPass.setBackground(Color.red);
        }
        if (retypePass.isEmpty()) {
            cretypePass.setBackground(Color.red);
        }
        if (currentPass.isEmpty()) {
            ccurrentPass.setBackground(Color.red);
        }
    }
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void ccurrentPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccurrentPassActionPerformed
        // TODO add your handling code here:
        ok.doClick();
    }//GEN-LAST:event_ccurrentPassActionPerformed

    private void cnewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnewPassActionPerformed
        // TODO add your handling code here:
        ok.doClick();
    }//GEN-LAST:event_cnewPassActionPerformed

    private void cretypePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cretypePassActionPerformed
        // TODO add your handling code here:
        ok.doClick();
    }//GEN-LAST:event_cretypePassActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JPasswordField ccurrentPass;
    private javax.swing.JPasswordField cnewPass;
    private javax.swing.JPasswordField cretypePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
