/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.mysql.jdbc.Blob;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tools.Transparent;
import model.Accounts;
import model.CurrentUser;
import model.OldUser;
import model.User;
import service.implementations.AccountsServiceImplementation;
import service.implementations.UserServiceImplementation;
import service.interfaces.AccountsServiceInterface;
import service.interfaces.UserServiceInterface;
import tools.ErrorException;
import tools.FormatTool;

/**
 *
 * @author sam
 */
public class profileFrame extends javax.swing.JDialog {

    private javax.swing.JFrame parentFrame;
    /**
     * Creates new form profileFrame
     */
    Object object;
    FormatTool formatTool = new FormatTool();
    private OldUser userOld;
    private User currentProfile;
    private JFrame chFrame;
    Home home = new Home();
    private CurrentUser userCurrent;

    public profileFrame(java.awt.Frame parent, boolean modal, User user, OldUser oldUser, javax.swing.JFrame currentUser) {
        super(parent, modal);
        Transparent trans = new Transparent();
        trans.TransparentDForm(this);
        initComponents();
        currentProfile = user;
        chFrame = currentUser;
        userOld = oldUser;
        this.setSize(500, 300);
        this.setLocationRelativeTo(null);
        this.parentFrame = (JFrame) parent;
        setProfile();
    }

    public void setProfile() {

        viewFullName.setText(currentProfile.getLastName() + ", " + currentProfile.getFirstName() + " " + currentProfile.getMiddleName());
        viewContactNo.setText(currentProfile.getContactNum());
        viewAddress.setText(currentProfile.getCity() + ", " + currentProfile.getProvince());
        viewEmailAddress.setText(currentProfile.getEmailAdd());
        if (currentProfile.getImage() != null) {
            object = currentProfile.getImage();
            if (object instanceof com.mysql.jdbc.Blob) {
                profilePic.setIcon(new javax.swing.ImageIcon(formatTool.convertToActualSizeImage((Blob) object, 2)));
            }
        } else {
            profilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/proIcon.jpg")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        profilePic = new javax.swing.JLabel();
        resetPass2 = new javax.swing.JButton();
        promote = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        viewEmailAddress = new javax.swing.JLabel();
        viewAddress = new javax.swing.JLabel();
        viewContactNo = new javax.swing.JLabel();
        viewFullName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(null);

        profilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/proIcon.jpg"))); // NOI18N
        profilePic.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(50, 120, 100, 100);

        resetPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/resetPass.jpg"))); // NOI18N
        resetPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPass2ActionPerformed(evt);
            }
        });
        jPanel5.add(resetPass2);
        resetPass2.setBounds(170, 240, 160, 30);

        promote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/promote.jpg"))); // NOI18N
        promote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promoteActionPerformed(evt);
            }
        });
        jPanel5.add(promote);
        promote.setBounds(50, 240, 120, 30);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.jpg"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel5.add(exit);
        exit.setBounds(360, 240, 95, 25);

        viewEmailAddress.setFont(new java.awt.Font("Segoe UI", 0, 18));
        viewEmailAddress.setForeground(new java.awt.Color(255, 255, 255));
        viewEmailAddress.setText("samrahbpetiilan@gmail.com");
        jPanel5.add(viewEmailAddress);
        viewEmailAddress.setBounds(170, 200, 310, 25);

        viewAddress.setFont(new java.awt.Font("Segoe UI", 0, 18));
        viewAddress.setForeground(new java.awt.Color(255, 255, 255));
        viewAddress.setText("Cagayan de Oro City, Misamis Oriental");
        jPanel5.add(viewAddress);
        viewAddress.setBounds(170, 170, 310, 25);

        viewContactNo.setFont(new java.awt.Font("Segoe UI", 0, 18));
        viewContactNo.setForeground(new java.awt.Color(255, 255, 255));
        viewContactNo.setText("09093196983");
        jPanel5.add(viewContactNo);
        viewContactNo.setBounds(170, 150, 310, 20);

        viewFullName.setFont(new java.awt.Font("Segoe UI", 0, 18));
        viewFullName.setForeground(new java.awt.Color(255, 255, 255));
        viewFullName.setText("Petiilan, Samra Hadji Basher");
        jPanel5.add(viewFullName);
        viewFullName.setBounds(170, 120, 310, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/profilerame.png"))); // NOI18N
        jPanel5.add(jLabel6);
        jLabel6.setBounds(0, 0, 502, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPass2ActionPerformed

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to reset this user's password to default?", "Confim", JOptionPane.YES_NO_OPTION);
        if (confirm == 0) {
            AccountsServiceInterface accountService = new AccountsServiceImplementation();
            Accounts acct = new Accounts();
            acct.setPassword("password");
            acct.setUserID(currentProfile.getUserID());
            try {
                accountService.editAccounts(acct);
            } catch (ErrorException ex) {
                Logger.getLogger(profileFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
            JOptionPane.showMessageDialog(this, "Faculty's password has been reset!\nDefault password is 'password'", "Successful", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_resetPass2ActionPerformed

    private void promoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promoteActionPerformed


        User userO = new User();
        User userN = new User();

        UserServiceInterface userService = new UserServiceImplementation();
        ArrayList<User> userSearch = new ArrayList<>();
        if (userO.getUserType() == 0) {
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to promote this user?\nCurrent Administrator will be demoted!", "Confim", JOptionPane.YES_NO_OPTION);
            if (confirm == 0) {
                try {
                    userSearch = userService.getUsers();
                } catch (ErrorException ex) {
                    Logger.getLogger(profileFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                for (User temp : userSearch) {
                    if (temp.getUserType() == 1) {
                        temp.setUserType(2);
                        try {
                            userService.editUserType(temp);
                        } catch (ErrorException ex) {
                            Logger.getLogger(profileFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                currentProfile.setUserType(1);
                try {
                    userService.editUserType(currentProfile);
                } catch (ErrorException ex) {
                    Logger.getLogger(profileFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                this.dispose();
                JOptionPane.showMessageDialog(this, "The user has been promoted!", "Successful", JOptionPane.INFORMATION_MESSAGE);
            }


        } else {

            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to promote this user?\n You will be demoted from bein the system administrator!", "Confim", JOptionPane.YES_NO_OPTION);
            if (confirm == 0) {
                userO.setUserType(2);
                userN.setUserType(1);
                userO.setUserID(userOld.getIdNumber());
                userN.setUserID(currentProfile.getUserID());

                UserServiceInterface userServiceNew = new UserServiceImplementation();
                UserServiceInterface userServiceOld = new UserServiceImplementation();
                try {
                    userServiceOld.editUserType(userO);
                    userServiceNew.editUserType(userN);
                } catch (ErrorException ex) {
                    Logger.getLogger(profileFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                chFrame.dispose();

                //cHome.setVisible(false);
                home.setVisible(true);
                this.dispose();
                JOptionPane.showMessageDialog(this, "You no longer have administrator rights!", "Successful", JOptionPane.INFORMATION_MESSAGE);
            }


        }

    }//GEN-LAST:event_promoteActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel profilePic;
    private javax.swing.JButton promote;
    private javax.swing.JButton resetPass2;
    private javax.swing.JLabel viewAddress;
    private javax.swing.JLabel viewContactNo;
    private javax.swing.JLabel viewEmailAddress;
    private javax.swing.JLabel viewFullName;
    // End of variables declaration//GEN-END:variables
}
