/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tools.Transparent;
import model.Accounts;
import model.CurrentUser;
import model.SecurityCode;
import service.implementations.AccountsServiceImplementation;
import service.implementations.SecurityCodeServiceImplementation;
import service.interfaces.AccountsServiceInterface;
import service.interfaces.SecurityCodeServiceInterface;
import tools.ErrorException;

/**
 *
 * @author sam
 */
public class setRegCode extends javax.swing.JDialog {

    private javax.swing.JFrame parentFrame;
    SecurityCodeServiceInterface securityCodeService;
    SecurityCode securityCode;
    /**
     * Creates new form setRegCode
     */
    private CurrentUser userCurrent;
    public setRegCode(javax.swing.JFrame parent, boolean modal,CurrentUser currentUser) {
        super(parent, modal);
        Transparent trans = new Transparent();
        trans.TransparentDForm(this);
        initComponents();
        this.setSize( 500, 315);
        this.setLocationRelativeTo(null);
        this.parentFrame = parent;
        userCurrent=currentUser;
        currentCode();
        code.setText(useCode());
        password.requestFocus();
    }
    
    private void currentCode(){
        securityCodeService = new SecurityCodeServiceImplementation();
        securityCode = new SecurityCode();
        try {
            securityCode = securityCodeService.getSecurityCode();
        } catch (ErrorException ex) {
            Logger.getLogger(setRegCode.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        currentCode.setText(securityCode.getSecurityCode().toString());
    }
    
    private String useCode ()
    {
        String useCode = Long.toHexString(Double.doubleToLongBits(Math.random()));
        String a = "";
        for ( int i = 5; i < 13; i++ )
            a += useCode.charAt(i);
        
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentCode = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        code = new javax.swing.JTextField();
        refresh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        currentCode.setFont(new java.awt.Font("Maiandra GD", 0, 20)); // NOI18N
        currentCode.setText("Current Code");
        getContentPane().add(currentCode);
        currentCode.setBounds(170, 110, 240, 30);

        jLabel5.setFont(new java.awt.Font("DK Crayon Crumble", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 190, 90, 40);

        password.setFont(new java.awt.Font("Maiandra GD", 0, 20)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(170, 190, 243, 31);

        ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/continue.jpg"))); // NOI18N
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(170, 240, 130, 30);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel.jpg"))); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(310, 240, 100, 30);

        code.setFont(new java.awt.Font("Maiandra GD", 0, 20)); // NOI18N
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeKeyReleased(evt);
            }
        });
        getContentPane().add(code);
        code.setBounds(170, 150, 243, 31);

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh.jpg"))); // NOI18N
        refresh.setBorder(null);
        refresh.setBorderPainted(false);
        refresh.setContentAreaFilled(false);
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh);
        refresh.setBounds(420, 160, 30, 30);

        jLabel8.setFont(new java.awt.Font("DK Crayon Crumble", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Code");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 115, 50, 30);

        jLabel7.setFont(new java.awt.Font("DK Crayon Crumble", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("New Code");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 155, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/setRegCode.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 510, 300);

        jLabel6.setFont(new java.awt.Font("DK Crayon Crumble", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Code");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 120, 60, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
      SecurityCodeServiceInterface securityService=new SecurityCodeServiceImplementation();
      AccountsServiceInterface accountService=new AccountsServiceImplementation();
      
      SecurityCode security= new SecurityCode();
      Accounts account=new Accounts();
      
   
      String codeInput=code.getText();
     System.out.print(userCurrent.getCurrentUser());
        try {
           account= accountService.getAccount(userCurrent.getCurrentUser());
        } catch (ErrorException ex) {
            ex.printStackTrace();
        }
       String passwordCheck=password.getText();
       
       if(account.getPassword().equals(passwordCheck)){
          security.setSecurityCode(codeInput);
            try {
                securityService.addSecurityCode(security);
            } catch (ErrorException ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "You have succesfully set the system registration code", "Succesful", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
       }else{
            JOptionPane.showMessageDialog(this, "Invalid Password", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_okActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        code.setText(useCode());
    }//GEN-LAST:event_refreshActionPerformed

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        // TODO add your handling code here:
        int keyNumber = evt.getKeyCode();
        if (keyNumber == KeyEvent.VK_ENTER) {
            ok.doClick();
    }
    }//GEN-LAST:event_passwordKeyReleased

    private void codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_codeKeyReleased

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
        ok.doClick();
    }//GEN-LAST:event_passwordActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
        ok.doClick();
    }//GEN-LAST:event_codeActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField code;
    private javax.swing.JLabel currentCode;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton ok;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
